---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitea-ingress
  namespace: gitea
spec:
  ingressClassName: nginx
  rules:
  - host: "gitea.paac-127-0-0-1.nip.io"
    http:
      paths:
      - backend:
          service:
            name: "gitea"
            port:
              number: 3000
        path: /
        pathType: Prefix
