issues:
  exclude-dirs:
    - vendor
    - pkg/provider/gitea/structs
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gosec
run:
  build-tags:
    - e2e
linters-settings:
  gocritic:
    disabled-checks:
      - unlambda
  errcheck:
    exclude-functions:
      - (*github.com/tektoncd/pipeline/vendor/go.uber.org/zap.SugaredLogger).Sync
      - flag.Set
      - logger.Sync
      - fmt.Fprintf
      - fmt.Fprintln
      - (io.Closer).Close
      - updateConfigMap
  gofumpt:
    extra-rules: true
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    #- containedctx
    #- contextcheck
    #- cyclop
    - decorder
    #- depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    #- exhaustruct
    - exportloopref
    - forbidigo
    - forcetypeassert
    #- funlen
    #- gci
    - ginkgolinter
    - gocheckcompilerdirectives
    #- gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    #- gocognit
    #- goconst
    - gocritic
    #- gocyclo
    - godot
    #- godox
    #- goerr113
    #- gofmt
    - gofumpt
    - goheader
    - goimports
    #- gomnd
    #- gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - importas
    #- inamedparam
    #- interfacebloat
    #- ireturn
    #- lll
    - loggercheck
    #- maintidx
    - makezero
    - mirror
    - misspell
    #- musttag
    - nakedret
    #- nestif
    - nilerr
    #- nilnil
    #- nlreturn
    - noctx
    #- nolintlint
    #- nonamedreturns
    - nosprintfhostport
    #- paralleltest
    #- perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    #- rowserrcheck
    - sloglint
    #- sqlclosecheck
    - staticcheck
    - stylecheck
    - tagalign
    #- tagliatelle
    - tenv
    - testableexamples
    # - testifylint
    #- testpackage
    #- thelper
    - tparallel
    #- unconvert
    - unparam
    - unused
    - usestdlibvars
    #- varnamelen
    #- wastedassign
    - whitespace
    #- wrapcheck
    #- wsl
    - zerologlint
