package cel

import (
	"bufio"
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"maps"
	"net/http"
	"os"
	"path"
	"path/filepath"
	"strconv"
	"strings"

	_ "embed"

	giteaStructs "code.gitea.io/gitea/modules/structs"
	"github.com/AlecAivazis/survey/v2"
	"github.com/chzyer/readline"
	"github.com/google/go-github/v71/github"
	pkgcel "github.com/openshift-pipelines/pipelines-as-code/pkg/cel"
	"github.com/openshift-pipelines/pipelines-as-code/pkg/cli"
	"github.com/openshift-pipelines/pipelines-as-code/pkg/formatting"
	"github.com/openshift-pipelines/pipelines-as-code/pkg/params/info"
	"github.com/openshift-pipelines/pipelines-as-code/pkg/params/triggertype"
	"github.com/openshift-pipelines/pipelines-as-code/pkg/provider/bitbucketcloud/types"
	providergh "github.com/openshift-pipelines/pipelines-as-code/pkg/provider/github"
	"github.com/spf13/cobra"
	gitlab "gitlab.com/gitlab-org/api/client-go"
	"golang.org/x/term"
)

const (
	bodyFileFlag    = "body"
	headersFileFlag = "headers"
	providerFlag    = "provider"
	githubTokenFlag = "github-token"
)

//go:embed templates/help.tmpl
var helpString string

// getHistoryFilePath returns the cross-platform path for the CEL history file.
func getHistoryFilePath() (string, error) {
	// Get user's home directory (works on Windows, macOS, Linux)
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}

	// Create the cache directory path
	cacheDir := filepath.Join(homeDir, ".cache", "tkn-pac")

	// Ensure the directory exists
	if err := os.MkdirAll(cacheDir, 0o755); err != nil {
		return "", err
	}

	// Return the full path to the history file
	return filepath.Join(cacheDir, "cel-history"), nil
}

func parseHTTPHeaders(s string) (map[string]string, error) {
	headers := make(map[string]string)
	scanner := bufio.NewScanner(strings.NewReader(s))
	for scanner.Scan() {
		line := scanner.Text()
		if strings.TrimSpace(line) == "" {
			continue
		}
		parts := strings.SplitN(line, ":", 2)
		if len(parts) != 2 {
			continue // or return error if strict
		}
		key := strings.TrimSpace(parts[0])
		value := strings.TrimSpace(parts[1])
		headers[key] = value
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	return headers, nil
}

// getHeaderCaseInsensitive performs case-insensitive header lookup.
func getHeaderCaseInsensitive(headers map[string]string, key string) string {
	// First try exact match
	if value, ok := headers[key]; ok {
		return value
	}
	// Then try case-insensitive match
	lowerKey := strings.ToLower(key)
	for k, v := range headers {
		if strings.ToLower(k) == lowerKey {
			return v
		}
	}
	return ""
}

// parseCurlHeaders extracts headers from a curl command string.
// This function parses curl commands like those generated by gosmee,
// extracting -H "Header: Value" flags.
func parseCurlHeaders(curlCommand string) (map[string]string, error) {
	headers := make(map[string]string)

	// Split the command into tokens, handling quoted strings
	tokens, err := splitCurlCommand(curlCommand)
	if err != nil {
		return nil, err
	}

	// Look for -H flags followed by header values
	for i := 0; i < len(tokens); i++ {
		if tokens[i] == "-H" && i+1 < len(tokens) {
			headerValue := tokens[i+1]
			// Parse "Header: Value" format
			if parts := strings.SplitN(headerValue, ":", 2); len(parts) == 2 {
				key := strings.TrimSpace(parts[0])
				value := strings.TrimSpace(parts[1])
				headers[key] = value
			}
			i++ // Skip the header value token
		}
	}

	return headers, nil
}

// splitCurlCommand splits a curl command string into tokens, properly handling quoted strings.
func splitCurlCommand(command string) ([]string, error) {
	var tokens []string
	var current strings.Builder
	inQuotes := false
	quoteChar := byte(0)

	for i := 0; i < len(command); i++ {
		char := command[i]

		switch {
		case !inQuotes && (char == '"' || char == '\''):
			inQuotes = true
			quoteChar = char
		case inQuotes && char == quoteChar:
			inQuotes = false
			quoteChar = 0
		case !inQuotes && (char == ' ' || char == '\t' || char == '\n'):
			if current.Len() > 0 {
				tokens = append(tokens, current.String())
				current.Reset()
			}
		default:
			current.WriteByte(char)
		}
	}

	if inQuotes {
		return nil, fmt.Errorf("unterminated quote in curl command")
	}

	if current.Len() > 0 {
		tokens = append(tokens, current.String())
	}

	// Ensure we always return a non-nil slice
	if tokens == nil {
		tokens = []string{}
	}

	return tokens, nil
}

// isGosmeeScript detects if the content appears to be a gosmee-generated shell script.
// It looks for patterns like "curl" commands with typical gosmee characteristics.
func isGosmeeScript(content string) bool {
	lines := strings.Split(content, "\n")
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		// Look for curl commands that contain -H flags (typical of webhook scripts)
		if strings.HasPrefix(trimmed, "curl") && strings.Contains(trimmed, "-H") {
			return true
		}
	}
	return false
}

// parseGosmeeScript extracts headers from a gosmee-generated shell script.
// It finds curl commands and extracts headers from their -H flags.
func parseGosmeeScript(content string) (map[string]string, error) {
	headers := make(map[string]string)
	lines := strings.Split(content, "\n")

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "curl") && strings.Contains(trimmed, "-H") {
			// Parse headers from this curl command
			curlHeaders, err := parseCurlHeaders(trimmed)
			if err != nil {
				continue // Skip malformed curl commands
			}
			// Merge headers (later commands override earlier ones)
			maps.Copy(headers, curlHeaders)
		}
	}

	if len(headers) == 0 {
		return nil, fmt.Errorf("no headers found in gosmee script")
	}

	return headers, nil
}

func eventFromGitHub(body []byte, headers map[string]string) (*info.Event, error) {
	event := info.NewEvent()
	event.EventType = getHeaderCaseInsensitive(headers, "X-GitHub-Event")
	event.Request.Payload = body
	event.Request.Header = http.Header{}
	for k, v := range headers {
		event.Request.Header.Set(k, v)
	}

	ghEvent, err := github.ParseWebHook(event.EventType, body)
	if err != nil {
		return nil, err
	}

	// Store the parsed GitHub event for CEL body access
	event.Event = ghEvent

	switch e := ghEvent.(type) {
	case *github.PushEvent:
		event.TriggerTarget = triggertype.Push
		event.Organization = e.GetRepo().GetOwner().GetLogin()
		event.Repository = e.GetRepo().GetName()
		event.DefaultBranch = e.GetRepo().GetDefaultBranch()
		event.URL = e.GetRepo().GetHTMLURL()
		sha := e.GetHeadCommit().GetID()
		if sha == "" {
			sha = e.GetAfter()
		}
		event.SHA = sha
		event.SHAURL = e.GetHeadCommit().GetURL()
		event.SHATitle = e.GetHeadCommit().GetMessage()
		event.Sender = e.GetSender().GetLogin()
		event.BaseBranch = e.GetRef()
		event.HeadBranch = event.BaseBranch
		event.BaseURL = event.URL
		event.HeadURL = event.URL
	case *github.PullRequestEvent:
		event.TriggerTarget = triggertype.PullRequest
		event.Organization = e.GetRepo().GetOwner().GetLogin()
		event.Repository = e.GetRepo().GetName()
		event.DefaultBranch = e.GetRepo().GetDefaultBranch()
		event.URL = e.GetRepo().GetHTMLURL()
		event.SHA = e.GetPullRequest().Head.GetSHA()
		event.BaseBranch = e.GetPullRequest().Base.GetRef()
		event.HeadBranch = e.GetPullRequest().Head.GetRef()
		event.BaseURL = e.GetPullRequest().Base.GetRepo().GetHTMLURL()
		event.HeadURL = e.GetPullRequest().Head.GetRepo().GetHTMLURL()
		event.Sender = e.GetPullRequest().GetUser().GetLogin()
		event.PullRequestNumber = e.GetPullRequest().GetNumber()
		event.PullRequestTitle = e.GetPullRequest().GetTitle()
		for _, l := range e.GetPullRequest().Labels {
			event.PullRequestLabel = append(event.PullRequestLabel, l.GetName())
		}
	case *github.IssueCommentEvent:
		event.TriggerTarget = triggertype.PullRequest
		if e.GetRepo() != nil {
			event.Organization = e.GetRepo().GetOwner().GetLogin()
			event.Repository = e.GetRepo().GetName()
			event.DefaultBranch = e.GetRepo().GetDefaultBranch()
			event.URL = e.GetRepo().GetHTMLURL()
		}
		event.Sender = e.GetSender().GetLogin()
		event.TriggerComment = e.GetComment().GetBody()
		if pr := e.GetIssue().GetPullRequestLinks(); pr != nil {
			num, err := strconv.Atoi(path.Base(pr.GetHTMLURL()))
			if err == nil {
				event.PullRequestNumber = num
			}
		}
	case *github.CommitCommentEvent:
		event.TriggerTarget = triggertype.Push
		event.Organization = e.GetRepo().GetOwner().GetLogin()
		event.Repository = e.GetRepo().GetName()
		event.DefaultBranch = e.GetRepo().GetDefaultBranch()
		event.URL = e.GetRepo().GetHTMLURL()
		event.Sender = e.GetSender().GetLogin()
		event.SHA = e.GetComment().GetCommitID()
		event.SHAURL = e.GetComment().GetHTMLURL()
		event.HeadBranch = event.DefaultBranch
		event.BaseBranch = event.DefaultBranch
		event.HeadURL = event.URL
		event.BaseURL = event.URL
		event.TriggerComment = e.GetComment().GetBody()
	default:
		return nil, fmt.Errorf("unsupported github event %T", e)
	}
	return event, nil
}

// eventFromGitHubWithProvider uses the actual GitHub provider to parse events with proper enrichment.
// This ensures consistency with the controller's event processing, but adapted for CLI usage.
func eventFromGitHubWithProvider(body []byte, headers map[string]string, githubToken string) (*info.Event, error) {
	// If no token provided, fall back to basic parsing
	if githubToken == "" {
		return eventFromGitHub(body, headers)
	}

	// Start with basic parsing to get initial event structure
	event, err := eventFromGitHub(body, headers)
	if err != nil {
		return nil, err
	}

	// Create a GitHub client for API calls
	ctx := context.Background()
	client, _, _ := providergh.MakeClient(ctx, "", githubToken)

	// Parse the GitHub webhook to get the typed event
	ghEvent, err := github.ParseWebHook(event.EventType, body)
	if err != nil {
		return event, nil // nolint: nilerr // fallback to basic parsing
	}

	// For specific event types that benefit from API enrichment, enhance them
	switch e := ghEvent.(type) {
	case *github.IssueCommentEvent:
		// For issue comments, we need to fetch PR details to get proper branch info
		if !e.GetIssue().IsPullRequest() {
			return event, nil // not a PR comment
		}

		prURL := e.GetIssue().GetPullRequestLinks().GetHTMLURL()
		prNumber, err := strconv.Atoi(path.Base(prURL))
		if err != nil {
			return event, nil // nolint: nilerr // fallback to basic parsing if URL parsing fails
		}

		// Fetch PR details
		pr, _, err := client.PullRequests.Get(ctx, event.Organization, event.Repository, prNumber)
		if err != nil {
			return event, nil // nolint: nilerr // fallback to basic parsing if API call fails
		}

		// Populate the missing fields that would be enriched by the provider
		event.SHA = pr.GetHead().GetSHA()
		event.SHAURL = fmt.Sprintf("%s/commit/%s", pr.GetHTMLURL(), pr.GetHead().GetSHA())
		event.PullRequestTitle = pr.GetTitle()
		event.HeadBranch = pr.GetHead().GetRef()
		event.BaseBranch = pr.GetBase().GetRef()
		event.HeadURL = pr.GetHead().GetRepo().GetHTMLURL()
		event.BaseURL = pr.GetBase().GetRepo().GetHTMLURL()
		event.DefaultBranch = pr.GetBase().GetRepo().GetDefaultBranch()
		event.URL = pr.GetBase().GetRepo().GetHTMLURL()

		// Add PR labels
		event.PullRequestLabel = nil // clear any existing labels
		for _, label := range pr.Labels {
			event.PullRequestLabel = append(event.PullRequestLabel, label.GetName())
		}

		return event, nil
	default:
		// For other events, basic parsing is sufficient
		return event, nil
	}
}

func pacParamsFromEvent(event *info.Event) map[string]string {
	repoURL := event.URL
	if event.CloneURL != "" {
		repoURL = event.CloneURL
	}
	gitTag := ""
	if after, ok := strings.CutPrefix(event.BaseBranch, "refs/tags/"); ok {
		gitTag = after
	}
	triggerComment := strings.ReplaceAll(strings.ReplaceAll(event.TriggerComment, "\r\n", "\\n"), "\n", "\\n")
	pullRequestLabels := strings.Join(event.PullRequestLabel, "\n")

	// Get event title based on trigger type
	eventTitle := event.PullRequestTitle
	if event.TriggerTarget == triggertype.Push {
		eventTitle = event.SHATitle
	}

	return map[string]string{
		"revision":            event.SHA,
		"repo_url":            repoURL,
		"repo_owner":          strings.ToLower(event.Organization),
		"repo_name":           strings.ToLower(event.Repository),
		"target_branch":       formatting.SanitizeBranch(event.BaseBranch),
		"source_branch":       formatting.SanitizeBranch(event.HeadBranch),
		"git_tag":             gitTag,
		"source_url":          event.HeadURL,
		"target_url":          event.BaseURL,
		"sender":              strings.ToLower(event.Sender),
		"target_namespace":    "",
		"event_type":          event.EventType,
		"event":               event.TriggerTarget.String(),
		"event_title":         eventTitle,
		"trigger_comment":     triggerComment,
		"pull_request_labels": pullRequestLabels,
	}
}

// detectProvider automatically detects the provider from headers and payload.
func detectProvider(headers map[string]string, body []byte) (string, error) {
	// Check for GitHub provider (most common)
	if getHeaderCaseInsensitive(headers, "X-GitHub-Event") != "" {
		// Check if it's actually Gitea (which also sets X-GitHub-Event)
		if getHeaderCaseInsensitive(headers, "X-Gitea-Event-Type") != "" {
			return "gitea", nil
		}
		return "github", nil
	}

	// Check for GitLab provider
	if getHeaderCaseInsensitive(headers, "X-Gitlab-Event") != "" {
		return "gitlab", nil
	}

	// Check for Bitbucket Cloud (uses User-Agent header)
	if userAgent := getHeaderCaseInsensitive(headers, "User-Agent"); userAgent != "" {
		if strings.Contains(strings.ToLower(userAgent), "bitbucket") {
			// Try to distinguish between Cloud and Data Center by payload structure
			var payload map[string]any
			if json.Unmarshal(body, &payload) == nil {
				if actor, ok := payload["actor"].(map[string]any); ok {
					if _, hasAccountID := actor["account_id"]; hasAccountID {
						return "bitbucket-cloud", nil
					}
					// Heuristic: if it has an `id` but not an `account_id`, assume it's Data Center
					if _, hasID := actor["id"]; hasID {
						return "bitbucket-datacenter", nil
					}
				}
			}
			// Default to cloud if we can't determine
			return "bitbucket-cloud", nil
		}
	}

	// Check for Gitea provider (backup check in case header is missing)
	if getHeaderCaseInsensitive(headers, "X-Gitea-Event-Type") != "" {
		return "gitea", nil
	}

	// Try to detect from payload structure as last resort
	var payload map[string]any
	if json.Unmarshal(body, &payload) == nil {
		// GitHub-like structure
		if repository, ok := payload["repository"].(map[string]any); ok {
			if htmlURL, ok := repository["html_url"].(string); ok {
				if strings.Contains(htmlURL, "github.com") {
					return "github", nil
				}
				if strings.Contains(htmlURL, "gitlab.com") || strings.Contains(htmlURL, "gitlab") {
					return "gitlab", nil
				}
			}
		}

		// GitLab-specific structure
		if project, ok := payload["project"].(map[string]any); ok {
			if webURL, ok := project["web_url"].(string); ok {
				if strings.Contains(webURL, "gitlab") {
					return "gitlab", nil
				}
			}
		}

		// Bitbucket-specific structure
		if repository, ok := payload["repository"].(map[string]any); ok {
			if links, ok := repository["links"].(map[string]any); ok {
				if html, ok := links["html"].(map[string]any); ok {
					if href, ok := html["href"].(string); ok {
						if strings.Contains(href, "bitbucket") {
							return "bitbucket-cloud", nil
						}
					}
				}
			}
		}
	}

	return "", fmt.Errorf("unable to detect provider from headers or payload")
}

func eventFromGitLab(body []byte, headers map[string]string) (*info.Event, error) {
	event := info.NewEvent()
	event.EventType = getHeaderCaseInsensitive(headers, "X-Gitlab-Event")
	event.Request.Payload = body
	event.Request.Header = http.Header{}
	for k, v := range headers {
		event.Request.Header.Set(k, v)
	}

	// Parse GitLab webhook payload
	eventInt, err := gitlab.ParseWebhook(gitlab.EventType(event.EventType), body)
	if err != nil {
		return nil, fmt.Errorf("failed to parse GitLab webhook: %w", err)
	}

	event.Event = eventInt

	// Extract common event information from GitLab payload
	switch gitEvent := eventInt.(type) {
	case *gitlab.MergeEvent:
		event.Organization = extractOrgFromPath(gitEvent.Project.PathWithNamespace)
		event.Repository = extractRepoFromPath(gitEvent.Project.PathWithNamespace)
		event.Sender = gitEvent.User.Username
		event.URL = gitEvent.Project.WebURL
		event.SHA = gitEvent.ObjectAttributes.LastCommit.ID
		event.HeadBranch = gitEvent.ObjectAttributes.SourceBranch
		event.BaseBranch = gitEvent.ObjectAttributes.TargetBranch
		event.PullRequestNumber = gitEvent.ObjectAttributes.IID
		event.PullRequestTitle = gitEvent.ObjectAttributes.Title
		event.TriggerTarget = triggertype.PullRequest
		if gitEvent.ObjectAttributes.Action == "close" {
			event.TriggerTarget = triggertype.PullRequestClosed
		}
	case *gitlab.PushEvent:
		if len(gitEvent.Commits) == 0 {
			return nil, fmt.Errorf("no commits attached to this push event")
		}
		lastCommitIdx := len(gitEvent.Commits) - 1
		event.Organization = extractOrgFromPath(gitEvent.Project.PathWithNamespace)
		event.Repository = extractRepoFromPath(gitEvent.Project.PathWithNamespace)
		event.Sender = gitEvent.UserUsername
		event.URL = gitEvent.Project.WebURL
		event.SHA = gitEvent.Commits[lastCommitIdx].ID
		event.SHATitle = gitEvent.Commits[lastCommitIdx].Title
		event.HeadBranch = gitEvent.Ref
		event.BaseBranch = gitEvent.Ref
		event.TriggerTarget = triggertype.Push
	case *gitlab.TagEvent:
		if len(gitEvent.Commits) == 0 {
			return nil, fmt.Errorf("no commits attached to this tag event")
		}
		lastCommitIdx := len(gitEvent.Commits) - 1
		event.Organization = extractOrgFromPath(gitEvent.Project.PathWithNamespace)
		event.Repository = extractRepoFromPath(gitEvent.Project.PathWithNamespace)
		event.Sender = gitEvent.UserUsername
		event.URL = gitEvent.Project.WebURL
		event.SHA = gitEvent.Commits[lastCommitIdx].ID
		event.SHATitle = gitEvent.Commits[lastCommitIdx].Title
		event.HeadBranch = gitEvent.Ref
		event.BaseBranch = gitEvent.Ref
		event.TriggerTarget = triggertype.Push
	default:
		return nil, fmt.Errorf("unsupported GitLab event type: %T", gitEvent)
	}

	return event, nil
}

func eventFromBitbucketCloud(body []byte, headers map[string]string) (*info.Event, error) {
	event := info.NewEvent()
	event.Request.Payload = body
	event.Request.Header = http.Header{}
	for k, v := range headers {
		event.Request.Header.Set(k, v)
	}

	// Parse Bitbucket Cloud webhook event type from headers (X-Event-Key), case-insensitive
	var eventType string
	for k, v := range headers {
		if strings.EqualFold(k, "X-Event-Key") {
			eventType = v
			break
		}
	}
	if eventType == "" {
		return nil, fmt.Errorf("missing X-Event-Key header for Bitbucket Cloud webhook")
	}

	event.EventType = eventType

	switch {
	case strings.HasPrefix(eventType, "pullrequest:"):
		var prEvent types.PullRequestEvent
		if err := json.Unmarshal(body, &prEvent); err != nil {
			return nil, fmt.Errorf("failed to parse Bitbucket Cloud pull request event: %w", err)
		}
		event.Event = &prEvent
		event.Organization = prEvent.Repository.Workspace.Slug
		repoParts := strings.Split(prEvent.Repository.FullName, "/")
		if len(repoParts) > 1 {
			event.Repository = repoParts[1]
		} else {
			event.Repository = prEvent.Repository.FullName
		}
		event.Sender = prEvent.PullRequest.Author.Nickname
		event.URL = prEvent.Repository.Links.HTML.HRef
		event.SHA = prEvent.PullRequest.Source.Commit.Hash
		event.HeadBranch = prEvent.PullRequest.Source.Branch.Name
		event.BaseBranch = prEvent.PullRequest.Destination.Branch.Name
		event.PullRequestNumber = prEvent.PullRequest.ID
		event.PullRequestTitle = prEvent.PullRequest.Title
		event.TriggerTarget = triggertype.PullRequest
		if eventType == "pullrequest:rejected" || eventType == "pullrequest:fulfilled" {
			event.TriggerTarget = triggertype.PullRequestClosed
		}
	case eventType == "repo:push":
		var pushEvent types.PushRequestEvent
		if err := json.Unmarshal(body, &pushEvent); err != nil {
			return nil, fmt.Errorf("failed to parse Bitbucket Cloud push event: %w", err)
		}
		event.Event = &pushEvent
		event.Organization = pushEvent.Repository.Workspace.Slug
		repoParts := strings.Split(pushEvent.Repository.FullName, "/")
		if len(repoParts) > 1 {
			event.Repository = repoParts[1]
		} else {
			event.Repository = pushEvent.Repository.FullName
		}
		event.Sender = pushEvent.Actor.Nickname
		event.URL = pushEvent.Repository.Links.HTML.HRef
		if len(pushEvent.Push.Changes) > 0 {
			event.SHA = pushEvent.Push.Changes[0].New.Target.Hash
			event.HeadBranch = pushEvent.Push.Changes[0].New.Name
			event.BaseBranch = pushEvent.Push.Changes[0].New.Name
		}
		event.TriggerTarget = triggertype.Push
	default:
		return nil, fmt.Errorf("unsupported Bitbucket Cloud event type: %s", eventType)
	}

	return event, nil
}

func eventFromBitbucketDataCenter(body []byte, headers map[string]string) (*info.Event, error) {
	event := info.NewEvent()
	event.Request.Payload = body
	event.Request.Header = http.Header{}
	for k, v := range headers {
		event.Request.Header.Set(k, v)
	}

	// Parse Bitbucket Data Center webhook event type from headers (X-Event-Key), case-insensitive
	var eventType string
	for k, v := range headers {
		if strings.EqualFold(k, "X-Event-Key") {
			eventType = v
			break
		}
	}
	if eventType == "" {
		return nil, fmt.Errorf("missing X-Event-Key header for Bitbucket Data Center webhook")
	}

	event.EventType = eventType

	switch {
	case strings.HasPrefix(eventType, "pr:"):
		// Parse as a generic pull request event structure
		var prData map[string]any
		if err := json.Unmarshal(body, &prData); err != nil {
			return nil, fmt.Errorf("failed to parse Bitbucket Data Center pull request event: %w", err)
		}
		event.Event = prData

		// Extract basic information from the payload structure
		if pullRequest, ok := prData["pullRequest"].(map[string]any); ok {
			if toRef, ok := pullRequest["toRef"].(map[string]any); ok {
				if repository, ok := toRef["repository"].(map[string]any); ok {
					if project, ok := repository["project"].(map[string]any); ok {
						if key, ok := project["key"].(string); ok {
							event.Organization = key
						}
					}
					if name, ok := repository["name"].(string); ok {
						event.Repository = name
					}
				}
				if displayID, ok := toRef["displayId"].(string); ok {
					event.BaseBranch = displayID
				}
			}
			if fromRef, ok := pullRequest["fromRef"].(map[string]any); ok {
				if displayID, ok := fromRef["displayId"].(string); ok {
					event.HeadBranch = displayID
				}
				if latestCommit, ok := fromRef["latestCommit"].(string); ok {
					event.SHA = latestCommit
				}
			}
			if id, ok := pullRequest["id"].(float64); ok {
				event.PullRequestNumber = int(id)
			}
			if title, ok := pullRequest["title"].(string); ok {
				event.PullRequestTitle = title
			}
		}
		if actor, ok := prData["actor"].(map[string]any); ok {
			if name, ok := actor["name"].(string); ok {
				event.Sender = name
			}
		}
		event.TriggerTarget = triggertype.PullRequest
	case eventType == "repo:refs_changed":
		// Parse as a generic push event structure
		var pushData map[string]any
		if err := json.Unmarshal(body, &pushData); err != nil {
			return nil, fmt.Errorf("failed to parse Bitbucket Data Center push event: %w", err)
		}
		event.Event = pushData

		// Extract basic information
		if repository, ok := pushData["repository"].(map[string]any); ok {
			if project, ok := repository["project"].(map[string]any); ok {
				if key, ok := project["key"].(string); ok {
					event.Organization = key
				}
			}
			if name, ok := repository["name"].(string); ok {
				event.Repository = name
			}
		}
		if actor, ok := pushData["actor"].(map[string]any); ok {
			if name, ok := actor["name"].(string); ok {
				event.Sender = name
			}
		}
		if changes, ok := pushData["changes"].([]any); ok && len(changes) > 0 {
			if change, ok := changes[0].(map[string]any); ok {
				if toHash, ok := change["toHash"].(string); ok {
					event.SHA = toHash
				}
				if refID, ok := change["refId"].(string); ok {
					event.HeadBranch = refID
					event.BaseBranch = refID
				}
			}
		}
		event.TriggerTarget = triggertype.Push
	default:
		return nil, fmt.Errorf("unsupported Bitbucket Data Center event type: %s", eventType)
	}

	return event, nil
}

func eventFromGitea(body []byte, headers map[string]string) (*info.Event, error) {
	event := info.NewEvent()
	event.EventType = getHeaderCaseInsensitive(headers, "X-Gitea-Event-Type")
	if event.EventType == "" {
		return nil, fmt.Errorf("missing X-Gitea-Event-Type header for Gitea webhook")
	}
	event.Request.Payload = body
	event.Request.Header = http.Header{}
	for k, v := range headers {
		event.Request.Header.Set(k, v)
	}

	// Parse Gitea webhook payload manually since parseWebhook is not exported
	var eventInt any
	switch event.EventType {
	case "push":
		eventInt = &giteaStructs.PushPayload{}
	case "pull_request":
		eventInt = &giteaStructs.PullRequestPayload{}
	case "issue_comment", "pull_request_comment":
		eventInt = &giteaStructs.IssueCommentPayload{}
	default:
		return nil, fmt.Errorf("unsupported Gitea event type: %s", event.EventType)
	}

	// Parse the payload into the eventInt interface
	if err := json.Unmarshal(body, &eventInt); err != nil {
		return nil, fmt.Errorf("failed to unmarshal Gitea payload: %w", err)
	}

	event.Event = eventInt

	// Extract common event information from Gitea payload
	switch gitEvent := eventInt.(type) {
	case *giteaStructs.PullRequestPayload:
		event.Organization = gitEvent.Repository.Owner.UserName
		event.Repository = gitEvent.Repository.Name
		event.Sender = gitEvent.Sender.UserName
		event.URL = gitEvent.Repository.HTMLURL
		event.SHA = gitEvent.PullRequest.Head.Sha
		event.HeadBranch = gitEvent.PullRequest.Head.Ref
		event.BaseBranch = gitEvent.PullRequest.Base.Ref
		event.PullRequestNumber = int(gitEvent.Index)
		event.PullRequestTitle = gitEvent.PullRequest.Title
		event.TriggerTarget = triggertype.PullRequest
		if gitEvent.Action == giteaStructs.HookIssueClosed {
			event.TriggerTarget = triggertype.PullRequestClosed
		}
	case *giteaStructs.PushPayload:
		event.Organization = gitEvent.Repo.Owner.UserName
		event.Repository = gitEvent.Repo.Name
		event.Sender = gitEvent.Sender.UserName
		event.URL = gitEvent.Repo.HTMLURL
		event.SHA = gitEvent.HeadCommit.ID
		if event.SHA == "" {
			event.SHA = gitEvent.Before
		}
		event.SHATitle = gitEvent.HeadCommit.Message
		event.HeadBranch = gitEvent.Ref
		event.BaseBranch = gitEvent.Ref
		event.TriggerTarget = triggertype.Push
	case *giteaStructs.IssueCommentPayload:
		if gitEvent.Issue.PullRequest == nil {
			return nil, fmt.Errorf("issue comment is not from a pull request")
		}
		event.Organization = gitEvent.Repository.Owner.UserName
		event.Repository = gitEvent.Repository.Name
		event.Sender = gitEvent.Sender.UserName
		event.URL = gitEvent.Repository.HTMLURL
		event.TriggerTarget = triggertype.PullRequest
		// For comments, we'll need to make additional API calls to get PR details
		// For now, we'll set basic info
		event.PullRequestNumber = extractPullRequestNumber(gitEvent.Issue.URL)
	default:
		return nil, fmt.Errorf("unsupported Gitea event type: %T", gitEvent)
	}

	return event, nil
}

// Helper functions.
func extractOrgFromPath(pathWithNamespace string) string {
	parts := strings.Split(pathWithNamespace, "/")
	if len(parts) >= 2 {
		return strings.Join(parts[:len(parts)-1], "/")
	}
	return ""
}

func extractRepoFromPath(pathWithNamespace string) string {
	parts := strings.Split(pathWithNamespace, "/")
	if len(parts) > 0 {
		return parts[len(parts)-1]
	}
	return ""
}

func extractPullRequestNumber(issueURL string) int {
	// Extract pull request number from issue URL
	// This is a simplified implementation
	parts := strings.Split(issueURL, "/")
	for i, part := range parts {
		if part == "issues" && i+1 < len(parts) {
			if num, err := strconv.Atoi(parts[i+1]); err == nil {
				return num
			}
		}
	}
	return 0
}

func Command(ioStreams *cli.IOStreams) *cobra.Command {
	var bodyFile, headersFile, provider, githubToken string

	cmd := &cobra.Command{
		Use:   "cel",
		Short: "Evaluate CEL expressions interactively with webhook payloads",
		Long: `Evaluate CEL expressions interactively with webhook payloads.

The command automatically detects the git provider from the webhook headers and payload structure.
Supported providers: GitHub, GitLab, Bitbucket Cloud, Bitbucket Data Center, and Gitea.

You can provide webhook payload and headers from files to test CEL expressions
that would be used in PipelineRun configurations.`,
		RunE: func(_ *cobra.Command, _ []string) error {
			body := map[string]any{}
			headers := map[string]string{}
			var bodyBytes []byte

			if bodyFile != "" {
				b, err := os.ReadFile(bodyFile)
				if err != nil {
					return err
				}
				bodyBytes = b
				if err := json.Unmarshal(b, &body); err != nil {
					return err
				}
			}

			if headersFile != "" {
				b, err := os.ReadFile(headersFile)
				if err != nil {
					return err
				}
				bs := bytes.TrimSpace(b)
				switch {
				case len(bs) > 0 && (bs[0] == '{' || bs[0] == '['):
					// JSON format headers
					if err := json.Unmarshal(bs, &headers); err != nil {
						return err
					}
				case isGosmeeScript(string(bs)):
					// Gosmee-generated shell script with curl commands
					h, err := parseGosmeeScript(string(bs))
					if err != nil {
						return err
					}
					headers = h
				default:
					// Plain HTTP headers format
					h, err := parseHTTPHeaders(string(bs))
					if err != nil {
						return err
					}
					headers = h
				}
			}
			// nolint:ineffassign,staticcheck
			pacParams := map[string]string{}
			// Auto-detect provider if not specified explicitly
			if provider == "auto" {
				detectedProvider, err := detectProvider(headers, bodyBytes)
				if err != nil {
					return fmt.Errorf("auto-detection failed: %w", err)
				}
				provider = detectedProvider
			}

			switch provider {
			case "github":
				var event *info.Event
				var err error
				if githubToken != "" {
					event, err = eventFromGitHubWithProvider(bodyBytes, headers, githubToken)
				} else {
					event, err = eventFromGitHub(bodyBytes, headers)
				}
				if err != nil {
					return err
				}
				pacParams = pacParamsFromEvent(event)
			case "gitlab":
				event, err := eventFromGitLab(bodyBytes, headers)
				if err != nil {
					return err
				}
				pacParams = pacParamsFromEvent(event)
			case "bitbucket-cloud":
				event, err := eventFromBitbucketCloud(bodyBytes, headers)
				if err != nil {
					return err
				}
				pacParams = pacParamsFromEvent(event)
			case "bitbucket-datacenter":
				event, err := eventFromBitbucketDataCenter(bodyBytes, headers)
				if err != nil {
					return err
				}
				pacParams = pacParamsFromEvent(event)
			case "gitea":
				event, err := eventFromGitea(bodyBytes, headers)
				if err != nil {
					return err
				}
				pacParams = pacParamsFromEvent(event)
			default:
				return fmt.Errorf("unsupported provider %s", provider)
			}

			fmt.Fprintln(ioStreams.Out, strings.TrimSpace(
				fmt.Sprintf(helpString, provider))+"\n")
			// Check if stdin is a terminal (interactive mode) or pipe/file (non-interactive mode)
			if term.IsTerminal(int(os.Stdin.Fd())) {
				// Get cross-platform history file path
				historyFile, err := getHistoryFilePath()
				if err != nil {
					// If we can't get history file path, continue without history
					historyFile = ""
				}

				// Interactive mode: use readline with history
				rl, err := readline.NewEx(&readline.Config{
					Prompt:            "CEL expression> ",
					HistoryFile:       historyFile,
					AutoComplete:      nil,
					InterruptPrompt:   "^C",
					EOFPrompt:         "exit",
					HistorySearchFold: true,
				})
				if err != nil {
					// Fallback to survey if readline fails
					for {
						var expr string
						if err := survey.AskOne(&survey.Input{Message: "CEL expression"}, &expr); err != nil {
							return err
						}
						if expr == "" {
							break
						}

						// Create files data structure (always empty in CLI mode)
						filesData := map[string]any{
							"all":      []string{},
							"added":    []string{},
							"deleted":  []string{},
							"modified": []string{},
							"renamed":  []string{},
						}

						val, err := pkgcel.Value(expr, body, headers, pacParams, filesData)
						if err != nil {
							fmt.Fprintln(ioStreams.Out, err)
						} else {
							fmt.Fprintf(ioStreams.Out, "%v\n", val)
						}
					}
					return nil
				}
				defer rl.Close()

				fmt.Fprintln(ioStreams.Out, "Type CEL expressions (use ↑/↓ for history, empty line to exit):")
				for {
					expr, err := rl.Readline()
					if err != nil {
						if errors.Is(err, readline.ErrInterrupt) || errors.Is(err, io.EOF) {
							break
						}
						return err
					}

					expr = strings.TrimSpace(expr)
					if expr == "" {
						break
					}

					// Create files data structure (always empty in CLI mode)
					filesData := map[string]any{
						"all":      []string{},
						"added":    []string{},
						"deleted":  []string{},
						"modified": []string{},
						"renamed":  []string{},
					}

					val, err := pkgcel.Value(expr, body, headers, pacParams, filesData)
					if err != nil {
						fmt.Fprintln(ioStreams.Out, err)
					} else {
						fmt.Fprintf(ioStreams.Out, "%v\n", val)
					}
				}
			} else {
				// Non-interactive mode: read from stdin
				scanner := bufio.NewScanner(os.Stdin)
				hasInput := false
				for scanner.Scan() {
					hasInput = true
					expr := strings.TrimSpace(scanner.Text())
					if expr == "" {
						continue
					}

					// Create files data structure (always empty in CLI mode)
					filesData := map[string]any{
						"all":      []string{},
						"added":    []string{},
						"deleted":  []string{},
						"modified": []string{},
						"renamed":  []string{},
					}

					val, err := pkgcel.Value(expr, body, headers, pacParams, filesData)
					if err != nil {
						fmt.Fprintln(ioStreams.Out, err)
					} else {
						fmt.Fprintf(ioStreams.Out, "%v\n", val)
					}
				}
				if err := scanner.Err(); err != nil {
					return fmt.Errorf("error reading from stdin: %w", err)
				}
				// If no input was provided via stdin in non-interactive mode, just exit gracefully
				// This allows the command to work in test scenarios
				if !hasInput {
					// Exit gracefully without error - this is expected when testing
					return nil
				}
			}
			return nil
		},
		Annotations: map[string]string{"commandType": "main"},
	}

	cmd.Flags().StringVarP(&bodyFile, bodyFileFlag, "b", "", "path to JSON body file")
	cmd.Flags().StringVarP(&headersFile, headersFileFlag, "H", "", "path to headers file (JSON, HTTP format, or gosmee-generated shell script)")
	cmd.Flags().StringVarP(&provider, providerFlag, "p", "auto", "payload provider (auto, github, gitlab, bitbucket-cloud, bitbucket-datacenter, gitea)")
	cmd.Flags().StringVarP(&githubToken, githubTokenFlag, "t", "", "GitHub personal access token for API enrichment (enables full event processing)")
	return cmd
}
