# Sample repository showing incoming webhook repository
---
apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: sample-app
  namespace: "sample-ci-webhook"
spec:
  # which URL this Repository handles
  url: "https://forge.com/owner/sample-app"
  incoming:
    - type: webhook-url
      # Targets support glob patterns with character classes and wildcards
      targets:
        - main                              # Exact match
        - develop                           # Exact match
        - feature/*                         # All feature branches (e.g., feature/new-ui)
        - release/v[0-9]*.[0-9]*.[0-9]*     # Semver releases (e.g., release/v1.2.3)
        - hotfix/[A-Z]*-[0-9]*              # JIRA pattern (e.g., hotfix/JIRA-123)
        - "{staging,production}/*"          # Alternation: staging/* or production/*
      secret:
        name: "webhook-secret"
        key: "webhook.secret"
  git_provider:
    type: github
    secret:
      name: "provider.secret"
      key: "tokenkey"
