apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipelines-as-code-controller
  namespace: pipelines-as-code
  labels:
    app.kubernetes.io/version: "devel"
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: pipelines-as-code
