---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: repositories.pac.tekton.dev
spec:
  group: pac.tekton.dev
  versions:
    - name: v1alpha1
      additionalPrinterColumns:
        - jsonPath: .spec.url
          name: URL
          type: string
        - jsonPath: .spec.branch
          name: Branch
          type: string          
        - jsonPath: .spec.namespace
          name: Namespace
          type: string 
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: Schema for the repository API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/  api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: Spec defines the desired state of Repository
              properties:
                url:
                  description: Repository URL
                  type: string
                branch:
                  description: Branch
                  type: string
                event_type:
                  description: Event Type
                  type: string                  
                namespace:
                  description: Namespace
                  type: string
              type: object
          type: object
  scope: Cluster
  names:
    plural: repositories
    singular: repository
    kind: Repository
    shortNames:
    - repo
