apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: boussole
  annotations:
    pipelinesascode.tekton.dev/pipeline: "https://raw.githubusercontent.com/openshift-pipelines/pac-boussole/main/pipeline-boussole.yaml"
    pipelinesascode.tekton.dev/on-comment: "^/(help|rebase|merge|lgtm|(cherry-pick|assign|unassign|label|unlabel)[ ].*)$"
    pipelinesascode.tekton.dev/max-keep-runs: "2"
spec:
  params:
    - name: trigger_comment
      value: |
        {{ trigger_comment }}
    - name: repo_owner
      value: "{{ repo_owner }}"
    - name: repo_name
      value: "{{ repo_name }}"
    - name: pull_request_number
      value: "{{ pull_request_number }}"
    - name: pull_request_sender
      value: "{{ body.issue.user.login }}"
    - name: git_auth_secret
      value: "{{ git_auth_secret }}"
    - name: comment_sender
      value: "{{ sender }}"
    - name: merge_method
      value: "squash"
  #
  # Optional parameters (value is the default):
  #
  # The key in git_auth_secret that contains the token (default: git-provider-token)
  # - name: git_auth_secret_key
  #   value: git-provider-token
  #
  # The /lgtm threshold needed of approvers for a PR to be approved (default: 1)
  # - name: lgtm_threshold
  #   value: "1"
  #
  # The permissionms the user need to trigger a lgtm
  # - name: lgtm_permissions
  #   value: "admin,write"
  #
  # The review event  when lgtm is triggered, can be APPROVE,
  # REQUEST_CHANGES, or COMMENT if setting to empty string it will be set as
  # PENDING
  # - name: lgtm_review_event
  #   value: "APPROVE"
  #
  pipelineRef:
    name: boussole
