baseURL = '/'
languageCode = 'en-us'
title = 'Pipelines as Code'
#theme = 'hugo-theme-learn'
theme = "hugo-book"
# Book configuration
disablePathToLower = true
enableGitInfo = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
custom_css = ["css/custom.css"]
disableLandingPageButton = false
BookLogo = "/pipelines-logo.svg"
BookRepo = "https://github.com/openshift-pipelines/pipelines-as-code"
BookEditPath = "edit/main/docs"

[menu]
[[menu.after]]
  name = "GitHub Pipelines as Code"
  url = "https://github.com/openshift-pipelines/pipelines-as-code"
  weight = 10

[[menu.after]]
  name = "TektonCD Documentation"
  url = "https://tekton.dev/docs/"
  weight = 20

[markup]
[markup.highlight]
style = "monokailight"
lineNumbersInTable = false
tabWidth = 2
guessSyntax = true
[markup.goldmark.renderer]
  unsafe = true
[markup.tableOfContents]
  startLevel = 2

[privacy.youtube]
privacyEnhanced = true
