name: Create and publish a Docker image to ghcr

on: ["push"]

env:
  REGISTRY: ghcr.io
  CONTROLLER_IMAGE_NAME: ${{ github.repository }}
  WATCHER_IMAGE_NAME: ${{ github.repository }}-watcher

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker (Controller)
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.CONTROLLER_IMAGE_NAME }}

      - name: Build and push controller docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          build-args: |
            COMPONENT=controller
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Extract metadata (tags, labels) for Docker (Watcher)
        id: meta-watcher
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.WATCHER_IMAGE_NAME }}

      - name: Build and push watcher docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          build-args: |
            COMPONENT=watcher
          push: true
          tags: ${{ steps.meta-watcher.outputs.tags }}
          labels: ${{ steps.meta-watcher.outputs.labels }}
