name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
jobs:
  deploy:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          persist-credentials: false
          # otherwise, there would be errors pushing refs to the destination repository.
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify --gc
        working-directory: ./docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public
