name: github pages

on:
  push:
    tags:
      - stable
    branches:
      - nightly

jobs:
  deploy:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify --gc
        working-directory: ./docs

      - name: Nightly Doc
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/nightly'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public
          publish_branch: docs-nightly

      - name: Stable Doc
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/tags/stable'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public
          publish_branch: docs-stable
